---
deployment:
  tasks:
    - export DEPLOYPATH=/home/teamrabb/cybertestinglab/

    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R sql-injection $DEPLOYPATH
    - /bin/cp -R xss $DEPLOYPATH
    - /bin/cp -R csrf $DEPLOYPATH
    - /bin/cp -R lfi $DEPLOYPATH
    - /bin/cp -R rfi $DEPLOYPATH
    - /bin/cp -R cors $DEPLOYPATH
    - /bin/cp -R cookie $DEPLOYPATH
    - /bin/cp -R redirect $DEPLOYPATH

    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp db.sql $DEPLOYPATH
    - /bin/cp Dockerfile $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp cookie_demo.php $DEPLOYPATH
    - /bin/cp reset_db.php $DEPLOYPATH
    - /bin/cp steal.php $DEPLOYPATH